// Builds "Bloody Voice — Game Design Document.docx"
const fs = require("fs");
const path = require("path");
const {
  Document, Packer, Paragraph, TextRun, AlignmentType, Footer, Header, PageNumber,
  PageOrientation, TableOfContents, PageBreak, BorderStyle,
} = require("docx");
const L = require("./lib");
const design = require("./part_design");
const city = require("./part_city");
const prompts = require("./part_prompts");
const tech = require("./part_tech");

// Usage: node tools/gdd/build.js  (needs: npm install docx@9 in tools/gdd)
const PROJECT = process.argv[2] || path.resolve(__dirname, "..", "..");
process.env.BV_ASSETS = path.join(PROJECT, "docs", "assets", "map");

const MARGIN = 1134; // 2 cm
const A4 = { width: 11906, height: 16838 };
const PORTRAIT_W = A4.width - 2 * MARGIN;
const LANDSCAPE_W = A4.height - 2 * MARGIN;

const footer = () => ({ default: new Footer({ children: [new Paragraph({
  alignment: AlignmentType.CENTER,
  children: [new TextRun({ text: "Bloody Voice — Game Design Document   ·   ", size: 16, color: L.C.muted }),
    new TextRun({ children: [PageNumber.CURRENT], size: 16, color: L.C.muted })],
})] }) });
const header = () => ({ default: new Header({ children: [new Paragraph({
  alignment: AlignmentType.RIGHT,
  border: { bottom: { style: BorderStyle.SINGLE, size: 4, color: L.C.border, space: 2 } },
  children: [new TextRun({ text: "HALLOWDEEP · v0.1", size: 15, color: L.C.muted })],
})] }) });
const portrait = { page: { size: A4, margin: { top: MARGIN, bottom: MARGIN, left: MARGIN, right: MARGIN } } };
const landscape = { page: { size: { width: A4.width, height: A4.height, orientation: PageOrientation.LANDSCAPE }, margin: { top: 800, bottom: 800, left: MARGIN, right: MARGIN } } };

const title = [
  new Paragraph({ spacing: { before: 2600 }, alignment: AlignmentType.CENTER, children: [new TextRun({ text: "BLOODY VOICE", font: L.FONT.head, size: 72, bold: true, color: L.C.accent })] }),
  new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 400 }, children: [new TextRun({ text: "Game Design Document", font: L.FONT.head, size: 36, color: L.C.head })] }),
  new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text: "A story-driven monster-hunting game with roguelike elements", italics: true, size: 24, color: L.C.muted })] }),
  new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 1800 }, children: [new TextRun({ text: "Deck-building combat · Investigation · Crafting · A living city", size: 22, color: L.C.muted })] }),
  new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text: "Version 0.1 — concept, city, generation prompts, roadmap, architecture", size: 20 })] }),
  new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text: "Engine: Godot 4.7 · GDScript", size: 20 })] }),
  new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text: "Date: 6 October 2026", size: 20 })] }),
  new Paragraph({ children: [new PageBreak()] }),
  L.H1nb("How to use this document"),
  L.Tbl(["If you need…", "Go to"], [
    ["The idea of the game in 2 minutes", "1. Vision"],
    ["Rules of a system (combat, gear, investigation…)", "3–12"],
    ["The city: layout, districts, layers", "13. The City of Hallowdeep (+ Figure 1 map page)"],
    ["How districts change after events", "14. The Living City, 15. World Events"],
    ["Prompts for ChatGPT image generation", "16. Art Direction and Generation Prompts"],
    ["Random content (contracts, rumors, shop)", "17. Procedural Generation"],
    ["What to build and in which order", "18. Development Roadmap"],
    ["How the code must be structured", "19. Technical Architecture"],
  ], [2, 2]),
  L.P(" "),
  L.P("**Files that belong to this document** (folder `docs/assets/map/`): `city_sketch.png` (top-down district sketch), `city_cross_section.png` (vertical layers), `city_grid.txt` (the same layout as text). They are generated by `tools/gen_city_sketch.py` from one layout definition, so they always agree."),
  L.Note("Update the table of contents in Word: right-click it → Update Field.", "Tip"),
  new Paragraph({ children: [new PageBreak()] }),
  new Paragraph({ children: [new TextRun({ text: "Contents", font: L.FONT.head, size: 36, bold: true, color: L.C.accent })], spacing: { after: 200 } }),
  new TableOfContents("Contents", { hyperlink: true, headingStyleRange: "1-2" }),
  new Paragraph({ children: [new PageBreak()] }),
];

L.setWidth(PORTRAIT_W);
const s1 = [...title, ...design(), ...city.intro()];
L.setWidth(LANDSCAPE_W);
const s2 = city.mapPage();
L.setWidth(PORTRAIT_W);
const s3 = [...city.afterMap(), ...prompts(), ...tech.generation(), ...tech.roadmap(), ...tech.architecture(), ...tech.appendices()];

const doc = new Document({
  creator: "Bloody Voice team", title: "Bloody Voice — Game Design Document", description: "GDD v0.1",
  styles: L.styles, numbering: L.numbering, features: { updateFields: true },  // Word refreshes the table of contents on open
  sections: [
    { properties: portrait, headers: header(), footers: footer(), children: s1.flat(Infinity) },
    { properties: landscape, headers: header(), footers: footer(), children: s2.flat(Infinity) },
    { properties: portrait, headers: header(), footers: footer(), children: s3.flat(Infinity) },
  ],
});

const out = path.join(PROJECT, "Bloody Voice - Game Design Document.docx");
Packer.toBuffer(doc).then((buf) => { fs.writeFileSync(out, buf); console.log("written", out, buf.length); });
