// Single source for district content: used by the city catalog AND by the art prompts.
module.exports.DISTRICTS = [
  {
    code: "CROWN", char: "C", name: "Crown Ward", cls: "Administrative / nobility", size: "Small (core)",
    where: "Exact centre of the platform, highest ground. Irregular star shape. Borders every inner district.",
    controller: "Crown Magistracy and old noble houses", danger: "A (contracts lead to P–D)",
    look: "Marble galleries, a citadel of black steel and white stone, clock towers on every square, gas lamps with brass cages, named streets, private gardens under glass domes.",
    areas: ["Citadel Square", "The Glass Gardens", "Gallery Row (noble mansions)", "Clockmakers' Steps"],
    landmarks: "1 — Crown Magistracy citadel",
    monsters: "Mimics and doubles, creatures living in mirrors and portraits, mind control. Nobles secretly dabble in black magic.",
    tags: "a servant 'acting differently'; mirrors covered with cloth; one more guest at the ball than invited",
    role: "Expensive secret contracts with strict deadlines; failure hurts reputation.",
    mood: "polished, cold, silent luxury hiding rot",
  },
  {
    code: "SILVERHILL", char: "S", name: "Silverhill", cls: "Religious", size: "Large (north-north-west, from the centre to the wall)",
    where: "North and north-west of the Crown Ward up to the Ringwall; west of the Hawk Gate post.",
    controller: "Church of the Pale Vault", danger: "A by day, P by night",
    look: "White cathedrals with moon-shaped rose windows, silver domes, convent walls, terraced cemetery down to the Ringwall, orphanage courtyards.",
    areas: ["Cathedral Close", "Convent of St. Aldric", "Terraced Cemetery", "Orphans' Stair"],
    landmarks: "4 — Cathedral of the Pale Vault; 5 — Convent of St. Aldric",
    monsters: "Sleepwalkers, 'Moon children', silver parasites, moth swarms. Hidden truth: the moon they worship is the Masked Moon, a creature wearing a god's skin.",
    tags: "at full moon; smells of incense and blood; the victim was smiling",
    role: "Long story chain of Chapter I; healing and holy consumables.",
    mood: "pale, sacred, moonlit, unsettling serenity",
  },
  {
    code: "VIGIL", char: "V", name: "Vigil Spire Ward", cls: "Military order", size: "Small wedge (north-east of the centre)",
    where: "Between Crown Ward and the Nordhal Quarter, north-east of the centre.",
    controller: "Order of the Iron Vigil", danger: "A",
    look: "A 300-metre honeycomb tower with 49 elevators, barracks, drill yards, archive halls, steel banners.",
    areas: ["The Spire", "Drill Yards", "Archive Halls"],
    landmarks: "2 — The Vigil Spire",
    monsters: "Rare: escaped evidence from archives, possessed knights.",
    tags: "armour found empty; orders given by no one; lights in the archive at night",
    role: "Dossiers on monsters (contract tags revealed early), knight armor blueprints.",
    mood: "disciplined, vertical, iron and lamplight",
  },
  {
    code: "LUMEN", char: "L", name: "Lumen Campus", cls: "University / science", size: "Medium (east of the centre)",
    where: "East of the Crown Ward, between Vigil Spire Ward (north) and Rowan Market (south-west).",
    controller: "Lumen Collegium", danger: "P (experiments escape)",
    look: "Lecture halls, glass laboratories, chimneys with coloured smoke, the Great Library with a brass dome, mechanical department workshops.",
    areas: ["Great Library", "Alchemy Wing", "Mechanical Department", "Lecture Quad"],
    landmarks: "3 — Great Library of the Collegium (the hero's Library action)",
    monsters: "Escaped 'Clay Saints' (artificial humans), victims of transmutation, living formulas.",
    tags: "smell of formalin; glass chiming; the skull opened neatly, like in a lecture",
    role: "Library actions; buyer of captured creatures; Mechanic blueprints.",
    mood: "clinical, curious, brass and glass, knowledge as power",
  },
  {
    code: "MARKET", char: "M", name: "Rowan Market", cls: "Trade", size: "Medium (south of the centre)",
    where: "Directly south of the Crown Ward, between the Avenues (west) and Lumen/Deepwright (east).",
    controller: "Rowan Exchange", danger: "A",
    look: "Covered rows, scales, crates, awnings, a central hall with a rowan tree carved in wood. The hero's shop is a wooden table with cards.",
    areas: ["Central Hall", "Covered Rows", "Crate Yards"],
    landmarks: "6 — Rowan Market, the shop table",
    monsters: "Smuggled 'sleeping' creatures in crates, wood parasites, a curse of greed (cursed object).",
    tags: "the cargo moved; a trader went mad with greed; roots through the cobbles",
    role: "The Shop location.",
    mood: "busy, warm lamplight, haggling, hidden contraband",
  },
  {
    code: "EXCHANGE", char: "X", name: "Rowan Exchange Posts", cls: "Trade enclaves", size: "Three small enclaves at the gates",
    where: "Hawk post at the north gate, Wolf post at the south-east gate, Bear post at the south-west gate. Together they form a triangle around the Crown Ward.",
    controller: "Rowan Exchange houses: Harrow (Hawk), Varga (Wolf), Brannoc (Bear)", danger: "A",
    look: "Fortified warehouses at the gates, totem carvings (eagle / wolf / bear), caravan yards, weighing towers.",
    areas: ["Hawk Post", "Wolf Post", "Bear Post"],
    landmarks: "14 — Hawk Gate post; 15 — Wolf Gate post; 16 — Bear Gate post",
    monsters: "Things that come in from the Mistveil with caravans.",
    tags: "fog on the cargo; a caravan arrived with one driver too many",
    role: "House-specific shop lines (Hawk = scopes, Bear = armor, Wolf = hunting mechanisms).",
    mood: "fortified, tribal-mercantile, fog at the gates",
  },
  {
    code: "AVENUES", char: "A", name: "The Numbered Avenues", cls: "Middle class (largest)", size: "Very large (west and south-west, from inner ring to the wall)",
    where: "Whole western half from the Morrell Ward to the Ringwall, and south-west to Scarlet Lantern Row; surrounds the Bear Gate post.",
    controller: "Nobody (formally the Magistracy, in practice the Iron Vigil)", danger: "A, with P hotspots",
    look: "An endless grid of identical streets: '12th Avenue', 'Street K'. Offices, shops, tenement houses, trams.",
    areas: ["4th Avenue", "23rd Avenue", "Tram Depot", "Letter Streets (A–Z)", "Laundry Canals"],
    landmarks: "13 — the quiet bookshop on 23rd Avenue (easter egg: its rumor can never be investigated — 'Contact not advised')",
    monsters: "Everyday horror: something in the drains, in the neighbours' cellar, on the last tram.",
    tags: "wet handprints on windows; children singing in the drains; the last tram arrived empty",
    role: "Most generated side contracts; good place to farm rumors.",
    mood: "grey routine, rain, repetition, lonely windows",
  },
  {
    code: "MORRELL", char: "H", name: "Morrell Ward", cls: "Medical", size: "Small-medium (west of the centre)",
    where: "West of the Crown Ward, between Silverhill (north) and the Avenues (south and west).",
    controller: "House Morrell", danger: "A",
    look: "Clinics, apothecaries, greenhouses with herbs, a morgue with green lamps.",
    areas: ["Apothecarium", "Greenhouses", "The Morgue"],
    landmarks: "10 — Morrell Apothecarium & clinic (Hunter's Fall wake-up point)",
    monsters: "Patients who did not die, disease-beings, infections from the Lower City.",
    tags: "the corpse was warm a week later; bitter herbal smell; nurses refuse the night shift",
    role: "Treatment of HP and the Voice; tonics; buys captured creatures.",
    mood: "sterile green light, herbs, quiet suffering",
  },
  {
    code: "NORDHAL", char: "N", name: "Nordhal Quarter", cls: "Hunters / working class — HOME", size: "Large (north-east, outer ring)",
    where: "North-east from the Hawk Gate post along the Ringwall down to the Grey Chapels.",
    controller: "Hunter crews and the old Nordhal families", danger: "P",
    look: "Dark brick, Nordhal runes on doors, forges, fighting pits, steam from bathhouses.",
    areas: ["Tavern Street", "Forge Row", "The Pits", "Old Rune Yard"],
    landmarks: "7 — Tavern 'The Lantern & Hook' (contract board); 8 — the hero's workshop-home",
    monsters: "Infected hunters turning into beasts — a familiar face from the tavern can become a contract.",
    tags: "a howl; human footprints turning into paws; smell of blood and medicine",
    role: "Hub: tavern, workshop, home. Blood formulas from the Pale Hounds or the Weavers.",
    mood: "rough, warm firelight, brotherhood and dread",
  },
  {
    code: "GREY", char: "G", name: "Grey Chapels", cls: "Slums at the platform edge", size: "Large (east, outer ring)",
    where: "East edge of the platform, between Nordhal (north) and Deepwright Lifts (south).",
    controller: "Nobody officially; the Grey Communion secretly", danger: "P",
    look: "Ruined chapels of a forgotten faith, shanty roofs, grey fog in cellars, bonfires.",
    areas: ["The Old Grey Chapel", "Shanty Roofs", "Edge Walk (railing over the abyss)"],
    landmarks: "12 — The Old Grey Chapel",
    monsters: "Fog corruption, cult summonings, rat swarms.",
    tags: "grey fog in the cellar; prayers to the god in the wall; people with grey eyes",
    role: "Contact with the Grey Communion; ichor; secret path down in Chapter II.",
    mood: "poverty, ash and fog, forbidden faith",
  },
  {
    code: "DEEPWRIGHT", char: "D", name: "Deepwright Lifts", cls: "Industrial", size: "Large (south-east)",
    where: "South-east between Lumen/Rowan Market and the Ringwall; contains the Wolf Gate post area.",
    controller: "Deepwright Company", danger: "P, D near the shafts",
    look: "Giant mine lifts going down through the platform, foundries, ore yards, machines roaring, workers in masks.",
    areas: ["Main Lifts", "Foundry Line", "Ore Yards", "Shaft 7 (sealed)"],
    landmarks: "9 — Deepwright Main Lifts (descent to the Lower City)",
    monsters: "Burrow Wyrm (rank D: digs, chitin shell, acid), creatures riding up the lifts.",
    tags: "walls eaten through; the floor collapsed; workers heard knocking from below",
    role: "Best district for Gears/Scrap; the way down in Chapter II.",
    mood: "industrial hell, sparks, steam, deep shafts",
  },
  {
    code: "SCARLET", char: "R", name: "Scarlet Lantern Row", cls: "Red-light / black market", size: "Medium (south, outer ring)",
    where: "South, between the Avenues (west) and Deepwright Lifts (east), down to the Ringwall.",
    controller: "Scarlet Supper", danger: "P–D",
    look: "Narrow alleys under red lanterns, brothels, gambling dens, underground auction houses, black magicians' parlours.",
    areas: ["Lantern Alley", "The Auction House", "Velvet Steps"],
    landmarks: "11 — Scarlet Supper auction house (black market)",
    monsters: "Illusions, blood curses, creatures summoned by clients.",
    tags: "a client left without a face; whispering in an unknown tongue; blood on the mirror",
    role: "Black market; Scarlet Supper contracts.",
    mood: "red light, perfume and blood, seductive danger",
  },
  {
    code: "WALL", char: "#", name: "The Ringwall", cls: "Fortification", size: "Ring around the platform",
    where: "Outer rim of the platform with three gates (Hawk N, Wolf SE, Bear SW).",
    controller: "Magistracy garrison", danger: "D during events",
    look: "Black steel bastion, searchlights aimed at the fog, watchtowers, drainage outlets.",
    areas: ["Hawk Gate", "Wolf Gate", "Bear Gate", "Wall Walk"],
    landmarks: "Gates 14–16",
    monsters: "Dreamspawn breaking through cracks in the Mistveil.",
    tags: "the searchlights went dark; fog crawled over the wall",
    role: "Fog Breach events; defence contracts.",
    mood: "siege, searchlights, endless fog",
  },
];

module.exports.LOWER = [
  ["Transition Zone", "Chapter II", "Slums hanging under the platform and on the ground, eternal shadow, dripping water, 'market from below'. Danger P."],
  ["Levels 6–5", "Chapter II", "Deepwright mines, villages of black-robed miners, Grey Communion rules. Trade with the Umbral kin. Danger P."],
  ["Level 4", "Chapter III", "Bodily mutations, alien ecology, fungal forests. Danger D."],
  ["Level 3", "Chapter III", "The 'no-longer-human': animal eyes, powers, their own laws and culture. Danger D."],
  ["Levels 2–1", "Chapter III", "Close to the Mistveil, cracks into the Underdream. Danger S."],
  ["Ruins of the Old Capital", "Chapter III / finale", "Under everything: catacombs, dragon bones (top crafting material), shards of the Ember Tablets, ancient shrines."],
];
